tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/core"
brew "antibody"
brew "asdf"
brew "bat"
brew "exa"
brew "gh"
brew "jq"
brew "mas"
brew "micro"
brew "node"
brew "pgcli"
brew "rclone"
brew "ripgrep"
brew "tldr"
brew "tree"
brew "wget"
brew "yarn"
brew "youtube-dl"
brew "heroku/brew/heroku"
cask "1password"
cask "alt-tab"
cask "appcleaner"
cask "authy"
cask "caprine"
cask "discord"
cask "docker"
cask "flux"
cask "google-chrome"
cask "icanhazshortcut"
cask "igdm"
cask "iina"
cask "inkscape"
cask "intellij-idea"
cask "iterm2"
cask "karabiner-elements"
cask "linear-linear"
cask "logitech-options"
cask "maccy"
cask "microsoft-teams"
cask "ngrok"
cask "nordvpn"
cask "notion"
cask "raycast"
cask "rectangle"
cask "slack"
cask "spotify"
cask "telegram"
cask "visual-studio-code"
cask "whatsapp"
cask "zoom"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Tailscale", id: 1475387142
mas "Xnip", id: 1221250572
